# Site settings
title: CR Blog
SEOTitle: 楚河的博客 | CR Blog
header-img: img/home-bg.jpg
email: churiver@outlook.com
description: ""
keyword: ""
url: "http://riverchu.github.io"                # your host, for absolute URL
baseurl: ""                                     # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     wflanker
zhihu_username:     none
github_username:    riverchu
#twitter_username:  riverchu
facebook_username:  haha



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","drafts","README.md","Gemfile","Gemfile.lock"]
# include: ["pages"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

collections:
  keynotes:
    output: true
    permalink: /keynotes/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "keynotes"
    values:
      layout: "keynote"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"

# Plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: riverchu

# Duoshuo settings
# duoshuo_username: riverblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 9666759a463f351bd8d2e6813e5f2a2b
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个脱离了高级趣味的人。"
sidebar-avatar: /img/avatar-cr.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "lijiejie",
        href: "http://www.lijiejie.com/"
    },{
        title: "Wait...",
        href: "#"
    }
]
